### ISSUE TITLE
output file is created but its empty(0.0Kb)

### ISSUE THREAD

**Issue by tenzinsamten** [googlesamples/android-Camera2Video#9]
i ran the application in my nexus 5 with android 6.0 , no crash its running fine but output file data size is 0.0kb even though i have recorded it for more than 15 sec. Please help..

**Comment by vkislicins** [comment]
Same problem on my Nexus 5 device (android 6.0) - 0kb file on output.

**Comment by xyz1hang** [comment]
This looks like a subtle bug ... I got it working on Nexus 5 running Android 6 (5.82MB file saved and it only saved part of the recording) once ... by changing the output file path to sdcard (you have to add WRITE_EXTERNAL_STORAGE to the VIDEO_PERMISSIONS Array at top of Camera2VideoFragment.java, in order to actually get the WRITE_EXTERNAL_STORAGE permission, specifying that in manifests doesn't work in debugging.) but then it started writing empty file again ...

**Comment by jparrish88** [comment]
Same issue on Nexus 6P (Android 6.0)- 0kb file on output.

**Comment by gbhall** [comment]
Same issue.

**Comment by EvilMo** [comment]
I just installed this and having the same issue on kalin linux output folder is empty?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
